export const arrAuthors = [
    {
        ID: 1,
        user_login: 'merc',
        user_pass: '$P$BX/D9f1X6RY2wSVEadIHtBKi9mIkQ1.',
        user_nicename: 'merc',
        user_email: 'and.exms@gmail.com',
        user_url: 'mercuryo.zazhigay.com',
        user_registered: '2022-08-01T10:44:32.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'merc',
    },
    {
        ID: 2,
        user_login: 'Nikolay Korinets',
        user_pass: '$P$BzU1IOlT7z7KesUio4LNNukRn85iCr1',
        user_nicename: 'nikolay-korinets',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Nikolay Korinets',
    },
    {
        ID: 3,
        user_login: 'Marya Kotelnik',
        user_pass: '$P$B/n2xwa89kyUFMg2t6xDYigQ2ioHGE1',
        user_nicename: 'marya-kotelnik',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Marya Kotelnik',
    },
    {
        ID: 4,
        user_login: 'Mercuryo',
        user_pass: '$P$BoL5/LoESZZL7YPIuUezahaNO2DXsw/',
        user_nicename: 'mercuryo',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Mercuryo',
    },
    {
        ID: 5,
        user_login: 'Alisa Tkach',
        user_pass: '$P$BCtZcSouSOquZjNmBS2.eXZAYTMav51',
        user_nicename: 'alisa-tkach',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Alisa Tkach',
    },
    {
        ID: 6,
        user_login: 'Nikolay Bocharov',
        user_pass: '$P$BUagFCTrGhJ6Lh7DuqG.2iNf/GAVK9.',
        user_nicename: 'nikolay-bocharov',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Nikolay Bocharov',
    },
    {
        ID: 7,
        user_login: 'Vyacheslav Akhmetov',
        user_pass: '$P$Bw5Rql1JzO8/zaPtAPaOdivQhIlGe3.',
        user_nicename: 'vyacheslav-akhmetov',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Vyacheslav Akhmetov',
    },
    {
        ID: 8,
        user_login: 'Andrey Ilinskiy',
        user_pass: '$P$BX2HZ60y7CGG/5VHHt645LU2gQkkuH.',
        user_nicename: 'andrey-ilinskiy',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Andrey Ilinskiy',
    },
    {
        ID: 9,
        user_login: 'Adam Berker',
        user_pass: '$P$BYvilQiZu6c56OTkMkeZT2KZhaiivS1',
        user_nicename: 'adam-berker',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Adam Berker',
    },
    {
        ID: 10,
        user_login: 'admin',
        user_pass: '$P$Bu3CY4wZESaGbNXBJVTXSbhdwshdMz1',
        user_nicename: 'admin',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'admin',
    },
    {
        ID: 11,
        user_login: 'Aleksandra Ivanova',
        user_pass: '$P$Bz2YU9eX/.bN4oARcs8FbEvByfLH4p1',
        user_nicename: 'aleksandra-ivanova',
        user_email: '',
        user_url: '',
        user_registered: '2022-08-22T16:21:51.000Z',
        user_activation_key: '',
        user_status: 0,
        display_name: 'Aleksandra Ivanova',
    },
];
